---
title: "College Scorecard"
author: "Mei Maddox, Mitchelle V., Conor Welsh"
date: "10/5/2021"
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(mosaic)
library(reshape)
```

## Directories

```{r}
rscripts <- "R Scripts"
```

## Dataset Preprocessing

**Subsetting the columns** isolates the columns which are relavent to answering the question we are asking.

```{r}
source(file.path(rscripts, "subset_data.R"))
csb21.sub <- subset.data(read.csv("Most-Recent-Cohorts-All-Data-Elements.csv", na.strings = c("NA", "PrivacySuppressed", "NULL")), seed=1234)
print(paste("Subsetted data has", dim(csb21.sub), c("rows", "columns")))
```

## Earnings Variable

```{r}
earnings.sub <- csb21.sub[,earnings.idx(csb21.sub)]

unlist(lapply(earnings.sub, function(x){
  1 - (sum(is.na(x)) / length(x))
}))

mean.sub <- melt(earnings.sub[c(1:3)])
ggplot(mean.sub, aes(x=variable, y=value, fill=variable)) + geom_violin(na.rm = T) + scale_y_log10() + geom_boxplot(width=0.2) + labs(x="Year", y="Earnings", title = "Mean Earnings") + theme(axis.text.x = element_blank())

median.sub <- melt(earnings.sub[c(4:6)])
ggplot(median.sub, aes(x=variable, y=value, fill=variable)) + geom_violin(na.rm = T) + scale_y_log10() + geom_boxplot(width=0.2) + labs(x="Year", y="Earnings", title = "Median Earnings") + theme(axis.text.x = element_blank())

sd.sub <- melt(earnings.sub[c(7:9)])
ggplot(mean.sub, aes(x=variable, y=value, fill=variable)) + geom_violin(na.rm = T) + scale_y_log10() + geom_boxplot(width=0.2) + labs(x="Year", y="Earnings", title = "Standard Earnings") + theme(axis.text.x = element_blank())
```


## Tuition Variable

````{r}
tuit.sub <- csb21.sub[,tuition.idx(csb21.sub)]

# NA check
  na.max <- 0.5
  
  na.prop <- apply(tuit.sub, 2, function(x) sum(is.na(x)/length(x)) )
  na.prop
  # amount of NAs greater than NA max?
  na.prop > na.max
  # all are less than 50% NAs except program year cost   # when using 50% NAs as NA max
  na.prop[na.prop > na.max]
  
# Favstats - mean, sd, quartiles, sample size, # of NAs
favstats(tuit.sub$COSTT4_A, na.rm=TRUE)
favstats(tuit.sub$COSTT4_P, na.rm=TRUE)
favstats(tuit.sub$TUITIONFEE_IN, na.rm=TRUE)
favstats(tuit.sub$TUITIONFEE_OUT, na.rm=TRUE)

# Checking Normality

densityplot(tuit.sub$COSTT4_A) #Right skewed
densityplot(tuit.sub$COSTT4_P) #Approx normal, some right skew
densityplot(tuit.sub$TUITIONFEE_IN) #Right skewed
densityplot(tuit.sub$TUITIONFEE_OUT) #Right skewed

# Calculating Z-scores to see standard devs from mean
# how many are higher/lower? does not fix normalization

in.z <- 0
tuit.sub$in.z <- (tuit.sub$TUITIONFEE_IN - mean(tuit.sub$TUITIONFEE_IN, na.rm=TRUE)) / sd(tuit.sub$TUITIONFEE_IN, na.rm=TRUE)
densityplot(tuit.sub$in.z)
out.z <- 0
tuit.sub$out.z <- (tuit.sub$TUITIONFEE_OUT - mean(tuit.sub$TUITIONFEE_OUT, na.rm=TRUE)) / sd(tuit.sub$TUITIONFEE_OUT, na.rm=TRUE)
densityplot(tuit.sub$out.z)
tuit.sub$comb.z <- tuit.sub$in.z + tuit.sub$out.z
comb.z <- 0
tuit.sub[order(tuit.sub$comb.z ),]
# skew still visible


tuit.sub <- tuit.sub[,1:4]
plot(tuit.sub, col = "blue", cex = 0.3 )
# tuition program year variable has no overlapping values with other variables (NAs)

boxplot(tuit.sub, xlab = "Type of Tuition", ylab = "Tuition Cost in Dollars", names = c("Academic Year", "Program Year", "In State", "Out of State"), col = c("light blue", "pink ", "light green", "tan"))

# Focusing on Tuition In & Out of State Variables
# csb21.sub
# Mean earnings 10 years after
plot(csb21.sub$MN_EARN_WNE_P10 ~ csb21.sub$TUITIONFEE_IN, col = "navy",cex = 0.5)
#Median 10 years after
plot(csb21.sub$MD_EARN_WNE_P10 ~ csb21.sub$TUITIONFEE_OUT, col = "dark green", cex = 0.5)
#SD 10 years 
plot(csb21.sub$SD_EARN_WNE_P10 ~ csb21.sub$TUITIONFEE_OUT, col = "red", cex = 0.5)

#Do Tuition Fee In or Out of State have a relationship with Median Earnings after 10 years? (using median bc of skew)

str(csb.2021$MD_EARN_WNE_P10)
str(csb21.sub$TUITIONFEE_IN)

t.test(as.integer(csb21.sub$MD_EARN_WNE_P10), csb21.sub$TUITIONFEE_IN)
t.test(as.integer(csb21.sub$MD_EARN_WNE_P10), csb21.sub$TUITIONFEE_OUT)
#approx 0 p-value for both test
```


