name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    
    - name: Install Dependencies
    - uses: r-lib/actions/setup-r-dependencies@v1
      with:
        needs: |
          Imports
    
    - name: Render Book
      run: |
        chmod +x ./_build.sh
        ./_build.sh

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _book
        SSH_PRIVATE_KEY: ${{ secrets.GITHUB_TOKEN }}
